#!/usr/bin/env python3
"""Generate release-date-dependent values consumed by CV.tex."""

from __future__ import annotations

import argparse
import json
from datetime import date, datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
JOBS_PATH = ROOT / "data" / "jobs.json"
OUTPUT_PATH = ROOT / "generated" / "cv-data.tex"
BADGE_PATH = ROOT / "data" / "experience.json"
DATE_FORMAT = "%d.%m.%Y"


def parse_date(value: str) -> date:
    return datetime.strptime(value, DATE_FORMAT).date()


def join_tasks(tasks: list[str]) -> str:
    """Join task fragments and capitalize the first letter of the result."""
    sentence = ", ".join(task.strip().rstrip(".") for task in tasks).strip()
    return sentence[:1].upper() + sentence[1:] + "."


def merged_intervals(jobs: list[dict], as_of: date) -> list[tuple[date, date]]:
    intervals = []
    for job in jobs:
        start = parse_date(job["startDate"])
        end = as_of if job["endDate"] is None else parse_date(job["endDate"])
        intervals.append((start, min(end, as_of)))

    intervals.sort()
    merged: list[list[date]] = []
    for start, end in intervals:
        if end < start:
            continue
        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)
    return [(start, end) for start, end in merged]


def experience_years(jobs: list[dict], as_of: date) -> int:
    days = sum((end - start).days + 1 for start, end in merged_intervals(jobs, as_of))
    return days // 365


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--date", help="Release date in YYYY-MM-DD format; defaults to today")
    args = parser.parse_args()

    as_of = date.today() if args.date is None else date.fromisoformat(args.date)
    jobs = json.loads(JOBS_PATH.read_text(encoding="utf-8"))
    years = experience_years(jobs, as_of)
    summaries = [join_tasks(job["tasks"]) for job in jobs]

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "% Auto-generated by scripts/generate_cv_data.py; do not edit.",
        f"\\def\\experienceYears{{{years}}}",
        f"\\def\\experienceAsOf{{{as_of.isoformat()}}}",
    ]
    for index, summary in enumerate(summaries, start=1):
        # Keep the joined, capitalized task sentence available for future CV sections.
        escaped = summary.replace("&", r"\\&").replace("%", r"\\%")
        lines.append(f"\\def\\job{index}Tasks{{{escaped}}}")
    OUTPUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    BADGE_PATH.parent.mkdir(parents=True, exist_ok=True)
    BADGE_PATH.write_text(
        json.dumps(
            {
                "schemaVersion": 1,
                "label": "experience",
                "message": f"{years} years",
                "color": "542B2B",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)}: {years} years as of {as_of.isoformat()}")


if __name__ == "__main__":
    main()
